// Action types
export const CLICK_THREAD  = 'CLICK_THREAD'
export const CREATE_MESSAGE  = 'CREATE_MESSAGE'
export const RECEIVE_RAW_CREATED_MESSAGE   = 'RECEIVE_RAW_CREATED_MESSAGE'
export const RAW_MESSAGES_REQUEST    = 'RAW_MESSAGES_REQUEST'

export const RECEIVE_RAW_MESSAGES = 'RECEIVE_RAW_MESSAGES'

export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES'

export const POST_NEW_MESSAGE = 'POST_NEW_MESSAGE'
